dist: bionic

language: cpp

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"

before_script:
    - mkdir build && cd build && CXX=g++ cmake ..

script:
    - make

os:
    - linux

addons:
    apt:
        packages:
            - build-essential
            - libboost-dev
            - cmake
            - qt5-default
            - qtbase5-dev-tools
            - qttools5-dev-tools
            - qttools5-dev
